lang: "ja"
title: "Kancollet"
short-description: >
    艦これの遠征・入渠・建造の終了を教えてくれるタイマー
email: "syusui.s@gmail.com"
description: >
    「艦隊これくしょん -艦これ-」の遠征・入渠・建造の終了を教えてくれるタイマーです。
    ブックマークレットとして実装されていますので、お気に入り・ブックマークに追加するだけで使えます。
baseurl: "/kancollet"
url: "https://syusui-s.github.io/kancollet"
twitter_username: syusui_s
github_username:  syusui-s

# Build settings
markdown: kramdown

exclude: ['vendor/']

links:
    - title: "News"
      url: "https://github.com/syusui-s/kancollet/releases"
    - title: "Wiki"
      url: "https://github.com/syusui-s/kancollet/wiki"
    - title: "View on Github"
      url: "https://github.com/syusui-s/kancollet/"
